#!/usr/bin/env tsx
/**
 * Generates TypeScript types from the Data 360 Connect API OpenAPI spec.
 * Usage: pnpm generate
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SPEC_PATH = path.resolve(
  ROOT,
  "../data-cloud/content/en-us/connectapi/references/spec/cdp-connect-api-Swagger.yaml",
);
const OUTPUT_PATH = path.resolve(ROOT, "src/generated/openapi.d.ts");

async function main() {
  console.log(`Reading spec from: ${SPEC_PATH}`);

  if (!fs.existsSync(SPEC_PATH)) {
    console.error(`Spec file not found: ${SPEC_PATH}`);
    process.exit(1);
  }

  const ast = await openapiTS(new URL(`file://${SPEC_PATH}`), {
    exportType: true,
  });

  const output = astToString(ast);

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(
    OUTPUT_PATH,
    `// Auto-generated by scripts/generate-types.ts — DO NOT EDIT\n${output}`,
  );

  console.log(`Generated types written to: ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error("Type generation failed:", err);
  process.exit(1);
});
