import type { ClientConfig } from "./core/types.js";
import { HttpClient } from "./core/http-client.js";
import { ActivationTargetsService } from "./resources/activation-targets.js";
import { ActivationsService } from "./resources/activations.js";
import { CalculatedInsightsService } from "./resources/calculated-insights.js";
import { ConnectionsService } from "./resources/connections.js";
import { ConnectorsService } from "./resources/connectors.js";
import { DataActionTargetsService } from "./resources/data-action-targets.js";
import { DataActionsService } from "./resources/data-actions.js";
import { DataCleanRoomService } from "./resources/data-clean-room.js";
import { DataGraphsService } from "./resources/data-graphs.js";
import { DataKitsService } from "./resources/data-kits.js";
import { DataLakeObjectsService } from "./resources/data-lake-objects.js";
import { DataModelObjectsService } from "./resources/data-model-objects.js";
import { DataSpacesService } from "./resources/data-spaces.js";
import { DataStreamsService } from "./resources/data-streams.js";
import { DataTransformsService } from "./resources/data-transforms.js";
import { DocumentAiService } from "./resources/document-ai.js";
import { IdentityResolutionsService } from "./resources/identity-resolutions.js";
import { InsightsService } from "./resources/insights.js";
import { MachineLearningService } from "./resources/machine-learning.js";
import { MetadataService } from "./resources/metadata.js";
import { PrivateNetworkRoutesService } from "./resources/private-network-routes.js";
import { ProfileService } from "./resources/profile.js";
import { QueryV1V2Service } from "./resources/query-v1v2.js";
import { QueryService } from "./resources/query.js";
import { SearchIndexService } from "./resources/search-index.js";
import { SegmentsService } from "./resources/segments.js";
import { UniversalIdLookupService } from "./resources/universal-id-lookup.js";

export class Data360Client {
  public readonly activationTargets: ActivationTargetsService;
  public readonly activations: ActivationsService;
  public readonly calculatedInsights: CalculatedInsightsService;
  public readonly connections: ConnectionsService;
  public readonly connectors: ConnectorsService;
  public readonly dataActionTargets: DataActionTargetsService;
  public readonly dataActions: DataActionsService;
  public readonly dataCleanRoom: DataCleanRoomService;
  public readonly dataGraphs: DataGraphsService;
  public readonly dataKits: DataKitsService;
  public readonly dataLakeObjects: DataLakeObjectsService;
  public readonly dataModelObjects: DataModelObjectsService;
  public readonly dataSpaces: DataSpacesService;
  public readonly dataStreams: DataStreamsService;
  public readonly dataTransforms: DataTransformsService;
  public readonly documentAi: DocumentAiService;
  public readonly identityResolutions: IdentityResolutionsService;
  public readonly insights: InsightsService;
  public readonly machineLearning: MachineLearningService;
  public readonly metadata: MetadataService;
  public readonly privateNetworkRoutes: PrivateNetworkRoutesService;
  public readonly profile: ProfileService;
  public readonly queryV1V2: QueryV1V2Service;
  public readonly query: QueryService;
  public readonly searchIndex: SearchIndexService;
  public readonly segments: SegmentsService;
  public readonly universalIdLookup: UniversalIdLookupService;

  constructor(config: ClientConfig) {
    const httpClient = new HttpClient(config);

    this.activationTargets = new ActivationTargetsService(httpClient);
    this.activations = new ActivationsService(httpClient);
    this.calculatedInsights = new CalculatedInsightsService(httpClient);
    this.connections = new ConnectionsService(httpClient);
    this.connectors = new ConnectorsService(httpClient);
    this.dataActionTargets = new DataActionTargetsService(httpClient);
    this.dataActions = new DataActionsService(httpClient);
    this.dataCleanRoom = new DataCleanRoomService(httpClient);
    this.dataGraphs = new DataGraphsService(httpClient);
    this.dataKits = new DataKitsService(httpClient);
    this.dataLakeObjects = new DataLakeObjectsService(httpClient);
    this.dataModelObjects = new DataModelObjectsService(httpClient);
    this.dataSpaces = new DataSpacesService(httpClient);
    this.dataStreams = new DataStreamsService(httpClient);
    this.dataTransforms = new DataTransformsService(httpClient);
    this.documentAi = new DocumentAiService(httpClient);
    this.identityResolutions = new IdentityResolutionsService(httpClient);
    this.insights = new InsightsService(httpClient);
    this.machineLearning = new MachineLearningService(httpClient);
    this.metadata = new MetadataService(httpClient);
    this.privateNetworkRoutes = new PrivateNetworkRoutesService(httpClient);
    this.profile = new ProfileService(httpClient);
    this.queryV1V2 = new QueryV1V2Service(httpClient);
    this.query = new QueryService(httpClient);
    this.searchIndex = new SearchIndexService(httpClient);
    this.segments = new SegmentsService(httpClient);
    this.universalIdLookup = new UniversalIdLookupService(httpClient);
  }
}
